spring.application.name=ds-catalog
# Garante que todas operacoes com o banco, transacao, e monitoramento de entidades jo JPA
# seja resolvido na camada de serviço e não chegue no contexto dos controllers.
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5432/ds-catalog
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true